language: golang

os:
  - osx
  - linux

sudo: true

golang:
  - "1.9"
  - "1.10"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export GOPATH=/Users/travis/go
    fi
  - env
  - mkdir -p $GOPATH/src/github.com/shana0440/watchdog
  - cp -r ./ $GOPATH/src/github.com/shana0440/watchdog
  - cd $GOPATH/src/github.com/shana0440/watchdog

install:
  - go get -t -d ./...

notifications:
  email:
    recipients:
      - shana0440@gmail.com
    on_success: always
    on_failure: always

script:
  - |
    set -e;
    echo "" > coverage.txt;

    for d in $(go list ./... | grep -v vendor); do \
        go test -race -coverprofile=profile.out -covermode=atomic $d; \
        if [ -f profile.out ]; then \
            cat profile.out >> coverage.txt; \
            rm profile.out; \
        fi; \
    done

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go build -o "watchdog-$TRAVIS_OS_NAME" main.go

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "watchdog-$TRAVIS_OS_NAME"
  on:
    tags: true
  skip_cleanup: true
